### ISSUE TITLE
(必須)flake8に準拠してほしい

### ISSUE THREAD

**Issue by shimizukawa** [yu-rasia/fruits-admin#1]
Pythonのコーディング規約チェックツール flake8 で警告が出ない状態にしましょう

**Comment by yu-rasia** [comment]
自分で書いたコードはflake8に準拠することが望ましい。
フレームワークによる自動生成ファイルとライブラリは対象外にして良い。
最終的に
`flake8 --exclude=migrations apps config data/gen_csv.py`
とすることに落ち着いた。

**Comment by shimizukawa** [comment]
閉じておきますー
